name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest, windows-latest, macOS-latest

    strategy:
      matrix:
        node-version: [12.13.0]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, yarn lint, yarn test, yarn build
        run: |
          yarn install
          yarn lint
          yarn test
          yarn build
        env:
          CI: true
